### PR TITLE
Adding cookie banner an google analytics.

### PR DESCRIPTION
**Pull request by nataliecarey**
This needs the GA ID and GTM ID added to it.

Right now it is only set up on v13 pages, there's also no mechanism to change cookie preferences.  I'm keen to make sure what I've done so far is along the right lines before going too much deeper.

### CODE REVIEW

**Comment by joelanman** [comment]
screenshot:
Cookies on GOV.UK Prototype kit Documentation We use some essential cookies to make this service work. We’d also like to use analytics cookies so we can understand how you use the service and make improvements. Accept analytics cookies Reject analytics cookies [View cookies](https://prototype-kit-docs-pr-214.herokuapp.com/docs/cookies)

**Comment by joelanman** [comment]
@nataliecarey if I accept then later reject cookies, I still have one GA cookie remain - tested on Design System and this doesnt happen (_gat_UA-26179049-11)

**Comment by nataliecarey** [comment]
@joelanman thanks for flagging that.  I can see where the code is meant to delete that cookie.  I'll dig in a bit further.

**Comment by nataliecarey** [comment]
@joelanman I've fixed the issue you mentioned with the cookie not being deleted.  As far as I can see this is ready to go.

**Comment by joelanman** [comment]
From reviewing with @oli-rose, can we have the banner content:

----
**Cookies on GOV.UK Prototype Kit**

We use some essential cookies to make this website work.

We’d also like to use analytics cookies so we can understand how you use the website and make improvements.

----

On the Cookies page, if I change my preference and click Save cookie settings, I don't get any confirmation. There should be a confirmation banner, same as Design System:

https://design-system.service.gov.uk/cookies/

**Comment by nataliecarey** [comment]
@joelanman I've made those changes.

**Review by joelanman — APPROVED** [review]

**Review by BenSurgisonGDS — APPROVED** [review]

**Pull request merged**
