### PR TITLE
Update step-by-step pattern examples on website

### PR DESCRIPTION
**Pull request by lfdebrux**
Updates step-by-step examples for docs website to match what will be in [GOV.UK Prototype Kit v12.2.0](https://github.com/alphagov/govuk-prototype-kit/issues/1508).

### CODE REVIEW

**Review by BenSurgisonGDS — APPROVED** [review]
LGTM

**Review by joelanman — COMMENTED** [review]
I think this needs a changelog entry as a breaking change

**Comment by lfdebrux** [comment]
> I think this needs a changelog entry as a breaking change

This is the change for the docs website, it doesn't have a changelog any more as it was removed in #27.

**Comment by joelanman** [comment]
o gosh sorry didnt realise it was the docs repo. In which case it looks good, we'll want to wait to merge until the change is released in the kit I think?

**Comment by lfdebrux** [comment]
> o gosh sorry didnt realise it was the docs repo. In which case it looks good, we'll want to wait to merge until the change is released in the kit I think?

Yeah, it's a captured as a step on the release ticket https://github.com/alphagov/govuk-prototype-kit/issues/1508.

**Review by joelanman — APPROVED** [review]

**Pull request merged**
