### PR TITLE
Add notification banner to documentation for old versions of kit

### LINKED ISSUE #79: Add a warning banner to v12 docs
## What

Add a warning banner to ever page of v12 docs as per the Figma design:

https://www.figma.com/file/sWnqT4u4uup91TuTe9T3tp/GOV.UK-Prototype-Kit-information?node-id=163%3A2

## Why

Users need to know they are looking at an old version of the site and a newer one is available

## Who needs to work on this

- developer

## Who needs to review this

- developer

## Done when

- [x] Visual design is confirmed by designer
- [x] Banner shows on every page of v12 docs

### PR DESCRIPTION
**Pull request by lfdebrux**
Closes #79

To see these changes you can visit https://prototype-kit-docs-pr-83.herokuapp.com/v12/docs/

### CODE REVIEW

**Review by joelanman — CHANGES_REQUESTED** [review]
thanks, on some pages it is full width, on others it isn't. Can we have it full width with the text inside 2/3 column? I think that last part is the standard way the component renders but just checking

also can we use a layout page for this? Instead of on every page individually?

not full width:
https://prototype-kit-docs-pr-83.herokuapp.com/v12/docs/install

**Comment by lfdebrux** [comment]
> thanks, on some pages it is full width, on others it isn't. Can we have it full width with the text inside 2/3 column? I think that last part is the standard way the component renders but just checking

[The guidance for the component says that it should be the same width as the page text](https://design-system.service.gov.uk/components/notification-banner/#how-it-works), can I confirm that is not what you want @joelanman?

> also can we use a layout page for this? Instead of on every page individually?

It depends, if we definitely want the banner to be full width on every page then that makes it easier to do.

**Comment by joelanman** [comment]
ah apologies for the confusion with the guidance. In this case we want the exact same thing on every page, so I think it works best as looking identical, full width everywhere

**Comment by lfdebrux** [comment]
I've updated the PR to use a full width notification banner everywhere.

**Comment by joelanman** [comment]
looks good! Adding a screenshot for reference:

Install guide for new users, showing the warning banner as described in this ticket

**Review by joelanman — APPROVED** [review]
looks good ta

**Pull request merged**
